platform :ios ,’8.0’

pod 'AFNetworking', '~> 3.0.4'
pod 'SDWebImage', '~> 3.7.5'
pod 'SVProgressHUD', '~> 2.0-beta8'
pod 'MJExtension', '~> 3.0.10'
pod 'MJRefresh', '~> 3.1.0'
pod "DACircularProgress"
pod 'pop', '~> 1.0.9'